### PR TITLE
adds sleep for get_notification_filters

### PR DESCRIPTION
**Pull request by rubenvitt**
ref: #44

### CODE REVIEW

**Comment by rubenvitt** [comment]
sorry, had some problems with my Git-setup 😂

**Comment by wesselt** [comment]
Hmm, looks to me like there's no guarantee that the 4th call will be to the notifcation filter.

Might be better to modify the call() function in lib/bunq.py to make sure the 3rd last call was 3 seconds old.  What do you think about that?

**Comment by rubenvitt** [comment]
Your comment makes totally sense. I think the different rate limits should be implemented. What do you think about it?

```
GET 3/3 seconds
POST 5/3 seconds
PUT 2/3 seconds
```

**Comment by wesselt** [comment]
Sure, that's even better!  There are already separate functions for GET, POST and PUT at the end of lib/bunq.py

**Comment by rubenvitt** [comment]
I'm implementing Python not very often, hopefully this one is good enough.

**Comment by wesselt** [comment]
Looks good, merged in!  Thanks

**Pull request merged**
